[package]
name = "phase-vocoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
cpal = "0.15.3"
realfft = "3.3.0"
rodio = { version = "0.19.0", features = ["mp3"] }
rustfft = "6.2.0"
